source "https://rubygems.org"

gem "activesupport", "7.0.4"
gem "dotenv", "2.7.6"
gem "foreman", "0.87.2"
gem "google-cloud-logging", "2.3.1", require: "google/cloud/logging"
gem "puma", "5.6.5"
gem "rack-contrib", "2.3.0"
gem "rack-cors", "1.1.1"
gem "rake", "13.0.6"
gem "selenium-webdriver", "4.1.0"
gem "sinatra", "2.1.0"
gem "sinatra-contrib", "2.1.0", require: false
gem "souls", "4.1.0"
gem "typhoeus", "1.4.0"
gem "zeitwerk", "2.6.1"

group :development, :test do
  gem "irb", "1.4.1"
  gem "rack-test", "1.1.0"
  gem "rspec", "3.10.0"
  gem "webmock", "3.14.0"
end

group :development do
  gem "rubocop", "1.26.0"
  gem "solargraph", "0.44.3"
end
