source "https://rubygems.org"

gem "activesupport", "7.0.2.3"
gem "dotenv", "2.7.6"
gem "foreman", "0.87.2"
gem "google-cloud-firestore", "2.6.6", require: "google/cloud/firestore"
gem "google-cloud-logging", "2.2.2", require: "google/cloud/logging"
gem "google-cloud-pubsub", "2.9.1", require: "google/cloud/pubsub"
gem "google-cloud-storage", "1.36.1", require: "google/cloud/storage"
gem "google-cloud-translate", "3.2.3", require: "google/cloud/translate"
gem "puma", "5.6.2"
gem "rack-contrib", "2.3.0"
gem "rack-cors", "1.1.1"
gem "rake", "13.0.6"
gem "selenium-webdriver", "4.1.0"
gem "sinatra", "2.1.0"
gem "sinatra-contrib", "2.1.0", require: false
gem "souls", "4.0.0"
gem "typhoeus", "1.4.0"
gem "zeitwerk", "2.5.4"

group :development, :test do
  gem "irb", "1.4.1"
  gem "rack-test", "1.1.0"
  gem "rspec", "3.10.0"
  gem "webmock", "3.14.0"
end

group :development do
  gem "rubocop", "1.26.0"
  gem "solargraph", "0.44.3"
end
