require "./app"

MAIN_APP_NAME = SOULs.configuration.app
APP_NAME = SOULs.configuration.app + FileUtils.pwd.split("/").last
APP_NAME_H = APP_NAME.gsub("_", "-")
PROJECT_ID = SOULs.configuration.project_id
REGION = SOULs.configuration.region
GCR_REGION = SOULs.configuration.gcr_region
PORT = 3001

task :build do
  system "docker build . -t #{APP_NAME}"
end

task :run do
  system "docker run --env-file .env -p #{PORT}:#{PORT} --restart always --name #{APP_NAME} #{APP_NAME}"
end

task :rm do
  system "docker rm -f #{APP_NAME}"
end

task :tag do
  system "docker tag #{APP_NAME}:latest #{GCR_REGION}/#{PROJECT_ID}/#{APP_NAME}:latest"
end
task :push do
  system "docker push #{GCR_REGION}/#{PROJECT_ID}/#{APP_NAME}:latest"
end
task :deploy do
  Rake::Task["build"].invoke
  SOULs::Painter.success("successfully built!")
  Rake::Task["tag"].invoke
  SOULs::Painter.success("successfully tagged!")
  Rake::Task["push"].invoke
  SOULs::Painter.success("successfully pushed!")
  Rake::Task["run_deploy"].invoke
  SOULs::Painter.success("successfully deployed!")
rescue StandardError => e
  SOULs::Painter.error(e)
end

task :run_deploy do
  system "gcloud run deploy souls-#{APP_NAME_H} \
  --service-account=#{MAIN_APP_NAME}@#{PROJECT_ID}.iam.gserviceaccount.com \
  --image=#{GCR_REGION}/#{PROJECT_ID}/#{APP_NAME}:latest \
  --memory=4Gi \
  --cpu=2 \
  --quiet \
  --region=#{REGION} \
  --project=#{PROJECT_ID} \
  --allow-unauthenticated \
  --platform=managed \
  --no-cpu-throttling \
  --port=8080 \
  --set-env-vars='SOULS_GCP_PROJECT_ID=#{PROJECT_ID}' \
  --set-env-vars='RUBY_YJIT_ENABLE=1'"
end
