module Types
  class ArticleType < BaseObject
    def self.implements: (*untyped) -> untyped
    def self.global_id_field: (:id) -> String
    def self.field: (:user, untyped, null: false) -> untyped
                  | (:title, String, null: true) -> String
                  | (:body, String, null: true) -> String
                  | (:category, String, null: true) -> String
                  | (:tags, [String], null: true) -> String
                  | (:slug, String, null: true) -> String
                  | (:published, Boolean, null: true) -> bool
                  | (:is_deleted, Boolean, null: true) -> bool
                  | (:created_at, String, null: true) -> String
                  | (:updated_at, String, null: true) -> String
  def self.edge_type: () -> untyped
    def self.connection_type: () -> untyped
  end
end
