target :app do
  repo_path "vendor/rbs/gem_rbs_collection/gems"
  library "pathname"
  library "logger"
  library "mutex_m"
  library "date"
  library "monitor"
  library "singleton"
  library "tsort"
  library "time"

  library "rack"

  library "activesupport"
  library "actionpack"
  library "activejob"
  library "activemodel"
  library "actionview"
  library "activerecord"
  library "railties"
  library "fileutils"
  library "graphql"
  signature "rbs"

  # check 'app'
  # check "lib/souls/api/generate/edge.rb"
  check "apps/scraper/app"
  check "apps/scraper/db/seeds.rb"
  check "apps/scraper/constants"
  check "apps/scraper/app.rb"
  check "apps/scraper/app"
  check "apps/scraper/db/seeds.rb"
  check "apps/scraper/constants"
  check "apps/scraper/app.rb"
  check "apps/scraper/app"
  check "apps/scraper/db/seeds.rb"
  check "apps/scraper/constants"
  check "apps/scraper/app.rb"
  check "apps/scraper/app"
  check "apps/scraper/db/seeds.rb"
  check "apps/scraper/constants"
  check "apps/scraper/app.rb"
  check "apps/scraper/app"
  check "apps/scraper/db/seeds.rb"
  check "apps/scraper/constants"
  check "apps/scraper/app.rb"
  check "apps/scraper/app"
  check "apps/scraper/db/seeds.rb"
  check "apps/scraper/constants"
  check "apps/scraper/app.rb"
  check "apps/scraper/app"
  check "apps/scraper/db/seeds.rb"
  check "apps/scraper/constants"
  check "apps/scraper/app.rb"
end
