---
name: activesupport
version: '6.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 6320a194c85afbf4ff332c3eb75fcae2a6518c92
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
