module Types
  class UserType < BaseObject
    def self.implements: (*untyped) -> untyped
    def self.global_id_field: (:id) -> String
    def self.field: (:uid, String, null: true) -> String
                  | (:username, String, null: true) -> String
                  | (:screen_name, String, null: true) -> String
                  | (:last_name, String, null: true) -> String
                  | (:first_name, String, null: true) -> String
                  | (:last_name_kanji, String, null: true) -> String
                  | (:first_name_kanji, String, null: true) -> String
                  | (:last_name_kana, String, null: true) -> String
                  | (:first_name_kana, String, null: true) -> String
                  | (:email, String, null: true) -> String
                  | (:tel, String, null: true) -> String
                  | (:icon_url, String, null: true) -> String
                  | (:birthday, String, null: true) -> String
                  | (:gender, String, null: true) -> String
                  | (:lang, String, null: true) -> String
                  | (:category, String, null: true) -> String
                  | (:roles_mask, Integer, null: true) -> Integer
                  | (:is_deleted, Boolean, null: true) -> bool
                  | (:created_at, String, null: true) -> String
                  | (:updated_at, String, null: true) -> String
  def self.edge_type: () -> void
    def self.connection_type: () -> void
  end
end
