module SoulsLogger
  def self.critical_log: (untyped) -> untyped
  def self.warning_log: (untyped) -> untyped
  def self.info_log: (untyped) -> untyped

  private
  def self.write_log: (untyped) -> untyped
end
