# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blog.proto", :syntax => :proto3) do
    add_message "Souls.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "Souls.HelloReply" do
      optional :message, :string, 1
    end
    add_message "Souls.Article" do
      optional :id, :string, 1
      optional :user_id, :string, 2
      optional :title, :string, 3
      optional :body, :string, 4
      optional :thumnail_url, :string, 5
      optional :public_date, :uint32, 6
      optional :article_category_id, :uint32, 7
      optional :is_public, :bool, 8
      repeated :tag, :string, 9
      optional :has_series, :bool, 10
      optional :series_id, :uint32, 11
      optional :episode_num, :uint32, 12
      optional :created_at, :message, 13, "google.protobuf.Timestamp"
      optional :updated_at, :message, 14, "google.protobuf.Timestamp"
    end
    add_message "Souls.GetArticlRequest" do
      optional :id, :uint32, 1
    end
    add_message "Souls.GetArticleReply" do
      optional :article, :message, 1, "Souls.Article"
    end
    add_message "Souls.GetArticlesRequest" do
      optional :search, :string, 1
      optional :limit, :uint32, 2
    end
    add_message "Souls.UpdateArticlesReply" do
      repeated :articles, :message, 1, "Souls.Article"
    end
    add_message "Souls.DeleteArticlRequest" do
      optional :id, :uint32, 1
    end
    add_message "Souls.DeleteArticleReply" do
      optional :article, :message, 1, "Souls.Article"
    end
    add_message "Souls.CreateArticleReply" do
      optional :article, :message, 1, "Souls.Article"
    end
  end
end

module Souls
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.HelloReply").msgclass
  Article = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.Article").msgclass
  GetArticlRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.GetArticlRequest").msgclass
  GetArticleReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.GetArticleReply").msgclass
  GetArticlesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.GetArticlesRequest").msgclass
  UpdateArticlesReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.UpdateArticlesReply").msgclass
  DeleteArticlRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.DeleteArticlRequest").msgclass
  DeleteArticleReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.DeleteArticleReply").msgclass
  CreateArticleReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Souls.CreateArticleReply").msgclass
end
module BlogPb
end
