FROM ruby:3.0.2

RUN apt-get update -qq && apt-get install -y nodejs redis-server 

USER root

RUN mkdir /myapp
WORKDIR /myapp

COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN gem install bundler:2.2.26
RUN bundle
COPY . /myapp

EXPOSE 4000
CMD ["foreman", "start", "-f", "Procfile.dev"]