source "https://rubygems.org"

gem "activesupport", "7.0.4"
gem "dotenv", "2.7.6"
gem "firebase_id_token", "2.4.0"
gem "foreman", "0.87.2"
gem "google-cloud-logging", "2.3.1", require: "google/cloud/logging"
gem "google-cloud-pubsub", "2.12.1", require: "google/cloud/pubsub"
gem "graphql", "2.0.14"
gem "grpc", "1.49.1"
gem "jwt", "2.3.0"
gem "pg", "1.4.4"
gem "puma", "5.6.5"
gem "rack-contrib", "2.3.0"
gem "rack-cors", "1.1.1"
gem "rake", "13.0.6"
gem "search_object_graphql", "1.0.2"
gem "sinatra", "3.0.2"
gem "sinatra-activerecord", "2.0.25", require: "sinatra/activerecord"
gem "sinatra-contrib", "2.1.0", require: false
gem "souls", "4.0.3"
gem "typhoeus", "1.4.0"
gem "zeitwerk", "2.6.1"

group :development, :test do
  gem "capybara", "3.37.1"
  gem "database_cleaner", "2.0.1"
  gem "factory_bot", "6.2.1"
  gem "faker", "2.23.0"
  gem "graphql_playground", "0.0.1"
  gem "rack-test", "2.0.2"
  gem "rspec", "3.11.0"
  gem "webmock", "3.18.1"
end

group :development do
  gem "rubocop", "1.36.0"
  gem "rubocop-graphql", "0.15.1"
  gem "solargraph", "0.47.2"
end
