source "https://rubygems.org"

gem "activesupport", "7.0.2.3"
gem "dotenv", "2.7.6"
gem "firebase_id_token", "2.4.0"
gem "foreman", "0.87.2"
gem "google-cloud-logging", "2.2.2", require: "google/cloud/logging"
gem "google-cloud-pubsub", "2.9.1", require: "google/cloud/pubsub"
gem "graphql", "1.13.10"
gem "grpc", "1.41.1"
gem "jwt", "2.3.0"
gem "pg", "1.3.4"
gem "puma", "5.6.2"
gem "rack-contrib", "2.3.0"
gem "rack-cors", "1.1.1"
gem "rake", "13.0.6"
gem "search_object_graphql", "1.0.2"
gem "sinatra", "2.1.0"
gem "sinatra-activerecord", "2.0.25", require: "sinatra/activerecord"
gem "sinatra-contrib", "2.1.0", require: false
gem "souls", "4.0.3"
gem "zeitwerk", "2.5.4"

group :development, :test do
  gem "capybara", "3.36.0"
  gem "database_cleaner", "2.0.1"
  gem "factory_bot", "6.2.0"
  gem "faker", "2.20.0"
  gem "gimei", "1.0.0"
  gem "graphql_playground", "0.0.1"
  gem "rack-test", "1.1.0"
  gem "rspec", "3.10.0"
  gem "webmock", "3.14.0"
end

group :development do
  gem "rubocop", "1.26.0"
  gem "rubocop-graphql", "0.13.0"
  gem "solargraph", "0.44.3"
end
