name: GemTest

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Run test
      run: |
        bundle exec rspec
