name: Run unit tests
on:
  push:

jobs:
  build_gem:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          bundler-cache: true
          ruby-version: 3.0.1
        
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          bundler-cache: true
          ruby-version: 3.0.1
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Check Gem Build
        run: |
          rake build gem
      - name: Check gem install
        run: |
          gem uninstall -aIx
          ls pkg | { read gemname; gem install pkg/$gemname }
          souls -v
