name: Run unit tests
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          bundler-cache: false
          ruby-version: 3.1
      - name: Install redis
        run: sudo apt-get install -y redis-tools redis-server libcurl3-dev
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Check gem build
        run: |
          bundle exec rake build
      - name: Check gem install
        run: |
          gem uninstall -aIx
          export gemname=$(ls pkg)
          gem install pkg/$gemname
          souls -v
